name: Create release PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write  # To commit the release changes
  pull-requests: write  # To create the pull request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run release script
        run: |
          scripts/update.sh

      - name: Create pull request
        if: ${{ env.update_tag_name != '' }}
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update to ${{ env.update_tag_name }}
          body: |
            This PR releases ${{ env.update_tag_name }}.
          commit-message: |
            Update to version ${{ env.update_tag_name }}
          branch: release/${{ env.update_tag_name }}
          delete-branch: true
          reviewers: pol-rivero
